# [mqtt]
# broker = "127.0.0.1"
# port = 1883
# qos = 1
# topic_sub = "node/status"
# topic_pub = "node/{node_id}/status"

# [broker]
# enabled = true
# bind_host = "0.0.0.0"
# bind_port = 1883

# [game]
# heartbeat_timeout = 600
# watchdog_interval = 30

# [message]
# msg_length = 7
# node_id_length = 5
